"""AI 资讯导航系统预设（迁移 seed 与运行时只读引用）。"""

from __future__ import annotations

from typing import TypedDict


class AiNewsPreset(TypedDict):
    slug: str
    url: str
    name: str
    description: str
    region: str
    icon: str
    letter: str
    color: str
    sort_order: int


SYSTEM_PRESETS: list[AiNewsPreset] = [
    {
        "slug": "openai",
        "url": "https://openai.com/news/",
        "name": "OpenAI 新闻",
        "description": "OpenAI 官方新闻与公告",
        "region": "international",
        "icon": "https://openai.com/favicon.ico",
        "letter": "O",
        "color": "#10A37F",
        "sort_order": 10,
    },
    {
        "slug": "anthropic",
        "url": "https://www.anthropic.com/news",
        "name": "Anthropic 新闻",
        "description": "Claude 及 Anthropic 官方动态",
        "region": "international",
        "icon": "https://www.anthropic.com/favicon.ico",
        "letter": "A",
        "color": "#CC785C",
        "sort_order": 20,
    },
    {
        "slug": "deepmind",
        "url": "https://deepmind.google/discover/blog/",
        "name": "Google DeepMind 博客",
        "description": "DeepMind 研究与产品博客",
        "region": "international",
        "icon": "https://deepmind.google/favicon.ico",
        "letter": "D",
        "color": "#4285F4",
        "sort_order": 30,
    },
    {
        "slug": "metaAi",
        "url": "https://ai.meta.com/blog/",
        "name": "Meta AI 博客",
        "description": "Llama 等 Meta AI 开源与产品资讯",
        "region": "international",
        "icon": "https://static.xx.fbcdn.net/rsrc.php/yB/r/qOSYt3pbp0K.ico",
        "letter": "M",
        "color": "#0668E1",
        "sort_order": 40,
    },
    {
        "slug": "xAi",
        "url": "https://x.ai/news",
        "name": "xAI 新闻",
        "description": "Grok 及 xAI 官方动态",
        "region": "international",
        "icon": "https://x.ai/favicon.ico",
        "letter": "X",
        "color": "#000000",
        "sort_order": 50,
    },
    {
        "slug": "huggingface",
        "url": "https://huggingface.co/blog",
        "name": "Hugging Face 博客",
        "description": "开源模型与 AI 社区动态",
        "region": "international",
        "icon": "https://huggingface.co/favicon.ico",
        "letter": "H",
        "color": "#FFD21E",
        "sort_order": 60,
    },
    {
        "slug": "huggingfacePapers",
        "url": "https://huggingface.co/papers",
        "name": "Hugging Face Papers",
        "description": "每日热门 AI 论文精选",
        "region": "international",
        "icon": "https://huggingface.co/favicon.ico",
        "letter": "P",
        "color": "#FFD21E",
        "sort_order": 70,
    },
    {
        "slug": "langchain",
        "url": "https://www.langchain.com/blog",
        "name": "LangChain 博客",
        "description": "LangChain 框架与 Agent 实践",
        "region": "international",
        "icon": "https://www.langchain.com/favicon.ico",
        "letter": "L",
        "color": "#1C3C3C",
        "sort_order": 80,
    },
    {
        "slug": "llamaindex",
        "url": "https://www.llamaindex.ai/blog",
        "name": "LlamaIndex 博客",
        "description": "RAG 与数据框架技术文章",
        "region": "international",
        "icon": "https://www.llamaindex.ai/favicon.ico",
        "letter": "Li",
        "color": "#7C3AED",
        "sort_order": 90,
    },
    {
        "slug": "nvidiaBlog",
        "url": "https://developer.nvidia.com/blog",
        "name": "NVIDIA 开发者博客",
        "description": "GPU、CUDA 与 AI 基础设施",
        "region": "international",
        "icon": "https://developer.nvidia.com/favicon.ico",
        "letter": "N",
        "color": "#76B900",
        "sort_order": 100,
    },
    {
        "slug": "arxiv",
        "url": "https://arxiv.org/list/cs.AI/recent",
        "name": "arXiv cs.AI 最新论文",
        "description": "人工智能方向最新预印本论文列表",
        "region": "international",
        "icon": "https://arxiv.org/static/browse/0.3.4/images/icons/favicon-32x32.png",
        "letter": "ar",
        "color": "#B31B1B",
        "sort_order": 110,
    },
    {
        "slug": "googleAi",
        "url": "https://blog.google/technology/ai/",
        "name": "Google AI 博客",
        "description": "Google AI 产品与技术新闻",
        "region": "international",
        "icon": "https://www.google.com/favicon.ico",
        "letter": "G",
        "color": "#4285F4",
        "sort_order": 120,
    },
    {
        "slug": "microsoftAi",
        "url": "https://blogs.microsoft.com/ai/",
        "name": "Microsoft AI 博客",
        "description": "Azure AI、Copilot 等企业 AI 动态",
        "region": "international",
        "icon": "https://www.microsoft.com/favicon.ico",
        "letter": "M",
        "color": "#00A4EF",
        "sort_order": 130,
    },
    {
        "slug": "mitTr",
        "url": "https://www.technologyreview.com/topic/artificial-intelligence/",
        "name": "MIT Technology Review · AI",
        "description": "麻省理工科技评论 AI 专题",
        "region": "international",
        "icon": "https://www.technologyreview.com/favicon.ico",
        "letter": "T",
        "color": "#000000",
        "sort_order": 140,
    },
    {
        "slug": "hnAi",
        "url": "https://hn.algolia.com/?q=AI",
        "name": "Hacker News · AI",
        "description": "开发者社区 AI 相关热门讨论",
        "region": "international",
        "icon": "https://news.ycombinator.com/favicon.ico",
        "letter": "Y",
        "color": "#FF6600",
        "sort_order": 150,
    },
    {
        "slug": "jiqizhixin",
        "url": "https://www.jiqizhixin.com/",
        "name": "机器之心",
        "description": "国内 AI 技术与产业媒体",
        "region": "domestic",
        "icon": "https://www.jiqizhixin.com/favicon.ico",
        "letter": "机",
        "color": "#1E88E5",
        "sort_order": 10,
    },
    {
        "slug": "qbitai",
        "url": "https://www.qbitai.com/",
        "name": "量子位",
        "description": "AI 产业、大模型与前沿报道",
        "region": "domestic",
        "icon": "https://www.qbitai.com/favicon.ico",
        "letter": "量",
        "color": "#1565C0",
        "sort_order": 20,
    },
    {
        "slug": "zhidx",
        "url": "https://www.zhidx.com/",
        "name": "智东西",
        "description": "智能硬件与 AI 产业资讯",
        "region": "domestic",
        "icon": "https://www.zhidx.com/favicon.ico",
        "letter": "智",
        "color": "#E53935",
        "sort_order": 30,
    },
    {
        "slug": "leiphone",
        "url": "https://www.leiphone.com/category/ai",
        "name": "雷锋网 · AI",
        "description": "雷锋网人工智能专栏",
        "region": "domestic",
        "icon": "https://www.leiphone.com/favicon.ico",
        "letter": "雷",
        "color": "#D32F2F",
        "sort_order": 40,
    },
    {
        "slug": "kr36",
        "url": "https://36kr.com/information/AI/",
        "name": "36氪 · AI",
        "description": "创投视角下的 AI 行业动态",
        "region": "domestic",
        "icon": "https://36kr.com/favicon.ico",
        "letter": "36",
        "color": "#286EFA",
        "sort_order": 50,
    },
    {
        "slug": "infoq",
        "url": "https://www.infoq.cn/",
        "name": "InfoQ 中文站",
        "description": "软件开发与 AI 技术深度内容",
        "region": "domestic",
        "icon": "https://www.infoq.cn/favicon.ico",
        "letter": "Q",
        "color": "#00B388",
        "sort_order": 60,
    },
]

DEFAULT_FAVORITE_SLUGS = [
    "huggingfacePapers",
    "jiqizhixin",
    "anthropic",
    "deepmind",
    "arxiv",
]

DEFAULT_FAVORITE_CUSTOM: list[dict[str, str]] = [
    {
        "url": "https://paperswithcode.com",
        "name": "Papers with Code",
        "region": "international",
    },
    {
        "url": "https://openai.com/research",
        "name": "OpenAI Research 博客",
        "region": "international",
    },
    {
        "url": "https://www.aiera.com.cn",
        "name": "新智元",
        "region": "domestic",
    },
    {
        "url": "https://www.zhihu.com/topic/19551275/hot",
        "name": "知乎·人工智能",
        "region": "domestic",
    },
]
